stages:
    - build
    - test
build:
    stage: build
    script:
        - '"nuget.exe" restore'
        - '"msbuild.exe" /p:VisualStudioVersion=15.0'
    artifacts:
        untracked: true
test:
    stage: test
    script:
        - '"mstest.exe" /testcontainer:StaffingPlanner.Tests/bin/Debug/StaffingPlanner.Tests.dll'

